# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.search_btn = QtWidgets.QPushButton(self.centralwidget)
        self.search_btn.setGeometry(QtCore.QRect(570, 90, 220, 30))
        self.search_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.search_btn.setObjectName("search_btn")
        self.search_le = QtWidgets.QLineEdit(self.centralwidget)
        self.search_le.setGeometry(QtCore.QRect(570, 130, 221, 30))
        self.search_le.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.search_le.setObjectName("search_le")
        self.change_type_btn = QtWidgets.QPushButton(self.centralwidget)
        self.change_type_btn.setGeometry(QtCore.QRect(570, 50, 220, 30))
        self.change_type_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.change_type_btn.setObjectName("change_type_btn")
        self.map_label = QtWidgets.QLabel(self.centralwidget)
        self.map_label.setGeometry(QtCore.QRect(10, 10, 550, 550))
        self.map_label.setText("")
        self.map_label.setObjectName("map_label")
        self.INF = QtWidgets.QLabel(self.centralwidget)
        self.INF.setGeometry(QtCore.QRect(569, 10, 220, 30))
        self.INF.setAlignment(QtCore.Qt.AlignCenter)
        self.INF.setWordWrap(False)
        self.INF.setObjectName("INF")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ЯндексЛицей Карты"))
        self.search_btn.setText(_translate("MainWindow", "Поиск"))
        self.change_type_btn.setText(_translate("MainWindow", "Смена вида карты"))
        self.INF.setText(_translate("MainWindow", "Доп. функции"))
